---
abstract: 'Dichotomize one or more numerical or categorical sequences into a single two-valued one'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Number::Misc: 1.0
  Scalar::Util: 1.18
  Statistics::Data: 0.02
  Statistics::Lite: 3.2
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Data-Dichotomize
provides:
  Statistics::Data::Dichotomize:
    file: lib/Statistics/Data/Dichotomize.pm
    version: 0.02
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
